name: Daily YouTube Video Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # Run once a day at midnight

jobs:
  fetch-videos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch latest videos
      run: |
        curl -s "https://www.youtube.com/feeds/videos.xml?channel_id=AsinaetNews" > videos.xml
        curl -s "https://www.youtube.com/feeds/videos.xml?channel_id=JayaPlusChennai" >> videos.xml
        python3 save_videos.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push videos
      run: |
        git config --global user.email "youremail@example.com"
        git config --global user.name "Your Name"
        git add videos.json
        git commit -m "Update videos"
        git push
